# Generated by Django 3.1.7 on 2021-03-15 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0003_pokemonentity"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemonentity",
            name="pokemon",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pokemon_entities.pokemon",
            ),
        ),
    ]
