# Generated by Django 3.1.7 on 2021-03-16 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0009_auto_20210316_1309"),
        ("pokemon_entities", "0009_auto_20210316_0731"),
    ]

    operations = []
